import { createInterface } from "node:readline";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const mode = process.argv[2] ?? "solve";
const send = (value) => process.stdout.write(`${JSON.stringify(value)}\n`);
let completed = false;

async function performRun(message) {
  if (completed) return;
  completed = true;
  send({ type: "agent_start" });
  send({ type: "turn_start" });
  if (mode === "generate-context") {
    await mkdir(".ctx", { recursive: true });
    await writeFile(
      "AGENTS.md",
      "# Mock repository context\n\nThis deterministic artifact verifies the isolated context-generation path.\n",
      "utf8",
    );
    await writeFile(
      path.join(".ctx", "architecture.md"),
      "# Architecture\n\nGenerated by the containerized CTXBench mock provider.\n",
      "utf8",
    );
  } else if (mode === "solve") {
    await writeFile(
      "ctxbench_mock_solution.txt",
      `Containerized mock solver completed. Prompt bytes: ${Buffer.byteLength(message)}\n`,
      "utf8",
    );
  }
  const assistant = {
    role: "assistant",
    content: [{ type: "text", text: `Mock ${mode} complete.` }],
    provider: "mock",
    model: "deterministic",
    usage: {
      input: 128,
      output: 32,
      cacheRead: 0,
      cacheWrite: 0,
      totalTokens: 160,
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
    },
  };
  send({ type: "message_end", message: assistant });
  send({ type: "turn_end", message: assistant, toolResults: [] });
  send({ type: "agent_end", messages: [assistant], willRetry: false });
  send({ type: "agent_settled" });
}

const input = createInterface({ input: process.stdin, crlfDelay: Infinity });
input.on("line", async (line) => {
  let command;
  try {
    command = JSON.parse(line);
  } catch {
    return;
  }
  if (command.type === "prompt") await performRun(String(command.message ?? ""));
  if (command.type === "get_session_stats") {
    send({
      type: "response",
      id: command.id,
      command: "get_session_stats",
      success: true,
      data: { inputTokens: 128, outputTokens: 32, cost: 0 },
    });
  }
  if (command.type === "abort") process.exit(1);
});

process.on("SIGTERM", () => process.exit(0));
