import { createInterface } from "node:readline";
import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";

const mode = process.argv[2] ?? "solve";
const send = (value) => process.stdout.write(`${JSON.stringify(value)}\n`);
let completed = false;

async function performRun(message) {
  if (completed) return;
  completed = true;
  send({ type: "agent_start", sessionPid: process.pid });
  send({ type: "turn_start" });
  // Synthetic workflow probes are available only through the explicit mock provider.
  if (message.startsWith("CTXBENCH_WORKFLOW_TEST:")) {
    const fixture = JSON.parse(message.slice("CTXBENCH_WORKFLOW_TEST:".length));
    const localPath = (relative) => {
      const resolved = path.resolve(relative);
      if (!resolved.startsWith(`${process.cwd()}${path.sep}`)) throw new Error("Invalid mock fixture path");
      return resolved;
    };
    try {
      if (fixture.expectedArgs && JSON.stringify(process.argv.slice(3)) !== JSON.stringify(fixture.expectedArgs)) throw new Error("Startup argv did not match the fixture.");
      if (fixture.requireFile) await access(localPath(fixture.requireFile));
      if (fixture.requireDependency && spawnSync("python", ["-c", "import ctxbench_fixture_dependency; assert ctxbench_fixture_dependency.VALUE == 42"]).status !== 0) throw new Error("Dependency was not available in the fresh agent session");
      if (fixture.fail) throw new Error("Requested mock step failure");
      if (fixture.writeFile) { const target = localPath(fixture.writeFile); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, "Workflow fixture\n"); }
    } catch (error) {
      send({ type: "response", id: "ctxbench-prompt", success: false, error: error.message });
      return;
    }
  }
  const delay = Number(process.env.CTXBENCH_TEST_DELAY_SECONDS ?? 0);
  if (delay > 0) await new Promise((resolve) => setTimeout(resolve, delay * 1000));
  if (mode === "generate-context") {
    await mkdir(".ctx", { recursive: true });
    await writeFile(
      "AGENTS.md",
      "# Mock repository context\n\nThis deterministic artifact verifies the isolated context-generation path.\n",
      "utf8",
    );
    await writeFile(
      path.join(".ctx", "architecture.md"),
      "# Architecture\n\nGenerated by the containerized CTXBench mock provider.\n",
      "utf8",
    );
  } else if (mode === "solve") {
    await writeFile(
      "ctxbench_mock_solution.txt",
      `Containerized mock solver completed. Prompt bytes: ${Buffer.byteLength(message)}\n`,
      "utf8",
    );
    // Exercise committed AND staged changes through the production patch extractor.
    spawnSync("git", ["add", "ctxbench_mock_solution.txt"]);
    spawnSync("git", ["-c", "user.name=Mock", "-c", "user.email=mock@ctxbench.invalid", "commit", "-qm", "Mock solution"]);
    await writeFile("ctxbench_mock_staged.txt", "Staged fixture\n");
    spawnSync("git", ["add", "ctxbench_mock_staged.txt"]);
  }
  const assistant = {
    role: "assistant",
    content: [{ type: "text", text: `Mock ${mode} complete.` }],
    provider: "mock",
    model: "deterministic",
    usage: {
      input: 128,
      output: 32,
      cacheRead: 0,
      cacheWrite: 0,
      totalTokens: 160,
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
    },
  };
  send({ type: "message_end", message: assistant });
  send({ type: "turn_end", message: assistant, toolResults: [] });
  send({ type: "agent_end", messages: [assistant], willRetry: false });
  send({ type: "agent_settled" });
}

const input = createInterface({ input: process.stdin, crlfDelay: Infinity });
input.on("line", async (line) => {
  let command;
  try {
    command = JSON.parse(line);
  } catch {
    return;
  }
  if (command.type === "prompt") await performRun(String(command.message ?? ""));
  if (command.type === "get_session_stats") {
    send({
      type: "response",
      id: command.id,
      command: "get_session_stats",
      success: true,
      data: { inputTokens: 128, outputTokens: 32, cost: 0 },
    });
  }
  if (command.type === "abort") process.exit(1);
});

process.on("SIGTERM", () => process.exit(0));
